import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "next-themes";
import StarryNightBackground from "./components/animatedBg/AnimatBg";
import SidePanel from "./components/sidePanel/SidePanel";
import TokenKeeper from "./tokenKeeper/TokenKeeper";
import ErrorHandler from "./components/errorHandler/ErrorHandler";
import ShowMsg from "./components/showMsg/ShowMsg";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "../../public/imgs/faceImg.png",
    
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >

      <NextIntlClientProvider >
         <ThemeProvider 
          attribute="data-theme" 
          defaultTheme="dark"
          enableSystem={false}
          storageKey="theme"
          >
            <StarryNightBackground />
            <SidePanel />
            <ErrorHandler />
            <TokenKeeper />
            <ShowMsg/>
              {children}
         </ThemeProvider>
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
